import type { Metadata } from "next";
import localFont from "next/font/local";
import "../themes/styles/globals.css";
import NavbarWrapper from "@/themes/components/navbar-wrapper/navbar-wrapper";

const hiraginoSans = localFont({
  src: "../themes/fonts/HiraginoSans.ttf",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={hiraginoSans.className}>
        <NavbarWrapper>{children}</NavbarWrapper>
      </body>
    </html>
  );
}
